# Generated by Django 3.0 on 2020-04-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
    ]
