# Generated by Django 3.0 on 2020-05-01 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='_user_friend_requests_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
